name: Print secrets
on: push
jobs:
  print-secret-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: "env var"
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: print env variable
      run: echo "MY_ENV_VAR = $MY_ENV_VAR"
    - name: print secret
      run: echo "MY_GITHUB_SECRET = ${{ secrets.MY_GITHUB_SECRET }}"
